---
output:
  show-stats: true
  sort-results: true
issues:
  max-same-issues: 10
  fix: true
linters:
  enable:
    - containedctx
    - copyloopvar
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - goconst
    - gocritic
    - gofumpt
    - gomnd
    - gosec
    - intrange
    - ireturn
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - perfsprint
    - predeclared
    - reassign
    - tagalign
